name = "InvestorStrategy"
# uuid = "..."  # Generate a new UUID
version = "0.1.0"

[deps]
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
GenieFramework = "a59fdf5c-6bf0-4f5d-949c-a137c9e2f353"
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"


[Genie]
instantiated_pwd = "/home/kawok/Documents/ANALOGIO/Julia/InvestorStrategy"
